### ISSUE TITLE
How to set theme on real project ?

### ISSUE THREAD

**Issue by xfathurrahman** [tuan-nguyen-van/4imageupload#1]
sorry im newbie.. can you tell me how to change the default theme to  "Large Upload Zone" ?  where i must change the code ?

`<div id="image-upload-demo">
                                <div id="iu-gallery"></div>
                                <div class="" style="display: inline-block; margin-right: 10px;">
                                    Other stuff
                                </div>
                                <div id="iu-image-upload-zone"></div>
                                <div class="" style="display: inline-block">
                                    Other stuff
                                </div>
                            </div>`

thanks in advance...

**Comment by tuan-nguyen-van** [comment]
Please go to the main website: 4imageupload.com to choose theme in the
theme section there

**Comment by xfathurrahman** [comment]
ahhh..  got it, so i choose it and download... thanks sir :) amazing code
